# Generated by Django 5.2.7 on 2025-10-06 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name": "Aula",
                "verbose_name_plural": "Aulas",
            },
        ),
        migrations.CreateModel(
            name="Persona",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="persona",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Producto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "epc",
                    models.CharField(max_length=96, unique=True, verbose_name="EPC"),
                ),
                ("nombre", models.CharField(max_length=255)),
                ("posicion", models.CharField(blank=True, max_length=100)),
                (
                    "n_serie",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Nº de serie"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="productos/"),
                ),
                ("estanteria", models.CharField(blank=True, max_length=100)),
                ("cantidad", models.FloatField(default=1.0)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "fds",
                    models.URLField(blank=True, verbose_name="FDS (hoja de datos)"),
                ),
                ("creado", models.DateTimeField(auto_now_add=True)),
                ("actualizado", models.DateTimeField(auto_now=True)),
                (
                    "aula",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos",
                        to="almacen.aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Prestamo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tomado_en", models.DateTimeField(auto_now_add=True)),
                ("devuelto_en", models.DateTimeField(blank=True, null=True)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prestamos",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prestamos",
                        to="almacen.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Préstamo",
                "verbose_name_plural": "Préstamos",
                "ordering": ["-tomado_en"],
            },
        ),
        migrations.CreateModel(
            name="Ubicacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ESTANTE", "En estantería"),
                            ("PERSONA", "En manos de una persona"),
                        ],
                        default="ESTANTE",
                        max_length=10,
                    ),
                ),
                ("estanteria", models.CharField(blank=True, max_length=100)),
                ("posicion", models.CharField(blank=True, max_length=100)),
                ("tomado_en", models.DateTimeField(blank=True, null=True)),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ubicaciones",
                        to="almacen.aula",
                    ),
                ),
                (
                    "persona",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="productos_tomados",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "producto",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ubicacion",
                        to="almacen.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ubicación",
                "verbose_name_plural": "Ubicaciones",
            },
        ),
    ]
