# Generated by Django 5.2.7 on 2025-11-17 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0003_ultima_aula_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="epc",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=96,
                null=True,
                unique=True,
                verbose_name="EPC",
            ),
        ),
    ]
