# Generated by Django 5.2.7 on 2025-11-17 19:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0004_persona_epc"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="usuario",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="prestamos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
