# Generated by Django 5.2.7 on 2025-11-25 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0005_alter_prestamo_usuario"),
    ]

    operations = [
        migrations.AddField(
            model_name="persona",
            name="aulas_access",
            field=models.ManyToManyField(
                blank=True,
                help_text="Aulas a las que esta persona tiene acceso. Si está vacío, tiene acceso a todas las aulas.",
                to="almacen.aula",
                verbose_name="Aulas accesibles",
            ),
        ),
    ]
