# Generated by Django 5.2.7 on 2025-12-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0006_add_aulas_access_to_persona"),
    ]

    operations = [
        migrations.AddField(
            model_name="aula",
            name="operation_mode",
            field=models.CharField(
                choices=[
                    ("WITH_PERSONA", "Con identificación de persona"),
                    ("WITHOUT_PERSONA", "Sin identificación de persona"),
                ],
                default="WITH_PERSONA",
                help_text="Modo de operación para esta aula: WITH_PERSONA requiere identificar persona para préstamos, WITHOUT_PERSONA permite préstamos sin identificación.",
                max_length=20,
                verbose_name="Modo de operación",
            ),
        ),
    ]
