# Generated by Django 5.2.7 on 2026-04-11 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0007_aula_operation_mode"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoRFID",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "imagen",
                    models.ImageField(upload_to="fotos_rfid/", verbose_name="Imagen"),
                ),
                (
                    "epc",
                    models.CharField(db_index=True, max_length=96, verbose_name="EPC"),
                ),
                (
                    "timestamp_captura",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Momento de captura (tz-aware, Europe/Madrid origen)",
                    ),
                ),
                (
                    "tamano_bytes",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Tamaño (bytes)"
                    ),
                ),
                (
                    "subida_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Subida en"),
                ),
                (
                    "aula",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fotos_rfid",
                        to="almacen.aula",
                    ),
                ),
            ],
            options={
                "verbose_name": "Foto RFID",
                "verbose_name_plural": "Fotos RFID",
                "ordering": ["-timestamp_captura"],
                "indexes": [
                    models.Index(fields=["epc"], name="almacen_fot_epc_705eef_idx"),
                    models.Index(
                        fields=["aula", "-timestamp_captura"],
                        name="almacen_fot_aula_id_b61848_idx",
                    ),
                ],
                "unique_together": {("epc", "timestamp_captura")},
            },
        ),
    ]
