# Generated by Django 5.2.7 on 2026-04-13 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0008_fotorfid"),
    ]

    operations = [
        migrations.CreateModel(
            name="LecturaHuerfana",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("epc", models.CharField(db_index=True, max_length=24)),
                ("timestamp", models.DateTimeField()),
                ("aula_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Lectura huerfana",
                "verbose_name_plural": "Lecturas huerfanas",
                "ordering": ["-timestamp"],
            },
        ),
    ]
