# Generated by Django 5.2.7 on 2026-04-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0009_lecturahuerfana"),
    ]

    operations = [
        migrations.AlterField(
            model_name="prestamo",
            name="tomado_en",
            field=models.DateTimeField(db_index=True),
        ),
    ]
