# Generated by Django 5.2.7 on 2026-04-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("almacen", "0010_alter_prestamo_tomado_en_remove_auto_now_add"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotorfid",
            name="epc",
            field=models.CharField(db_index=True, max_length=24, verbose_name="EPC"),
        ),
        migrations.AlterField(
            model_name="persona",
            name="epc",
            field=models.CharField(
                blank=True,
                default=None,
                max_length=24,
                null=True,
                unique=True,
                verbose_name="EPC",
            ),
        ),
        migrations.AlterField(
            model_name="producto",
            name="epc",
            field=models.CharField(max_length=24, unique=True, verbose_name="EPC"),
        ),
    ]
